Allow clients and servers to operate without names
canonical/dbus.dart pull request #363
Opened 2023-09-21 00:30 UTC by robert-ancell

Allow clients and servers to operate without names, for example if using D-Bus

for a simple client-server relationship and not in the more common client-client.

This only supports method calls from the client to the server at present.

2023-09-21 07:44 UTC, sergio-costas reviewed
Looks good. I'll try to test this with my code.

2023-09-21 11:58 UTC, sergio-costas requested changes
It begins to work, but still triggers a new exception:

```
flutter: ERROR ubuntu_init: Unhandled exception
	DBusUnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: No such method “GetNameOwner”
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1121)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:617)
<asynchronous suspension>
#2      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:457)
<asynchronous suspension>
#3      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:633)
```

2023-09-21 12:19 UTC, sergio-costas commented
The problem seems to be when creating a DBusRemoteObjectSignal object, to receive signals.

2023-09-22 02:02 UTC, robert-ancell commented
I think this branch should be able to receive signals now, though I haven't tested it. I'm landing some structural changes on main then I'll being these over after.

2023-09-22 02:40 UTC, robert-ancell commented
In fact, I think this should now work from main, I haven't got a test for the method calls there because I'm not sure the best way to expose them server side, but the code should support both methods and signals.

2023-09-22 05:48 UTC, CarlosNihelton commented
It would be good to have a test case matching what @sergio-costas is doing.

2023-09-22 08:41 UTC, sergio-costas commented
@robert-ancell I'll test this right now. Thanks!

2023-09-22 10:07 UTC, sergio-costas commented
This code works great, it talks flawlessly with GDM.

2023-09-22 14:05 UTC, sergio-costas approved these changes
LGTM

2023-09-27 04:12 UTC, CarlosNihelton approved these changes
LGTM 👍🏽

2023-10-02 03:39 UTC, robert-ancell commented
Is everything you need working on main? This PR is too difficult to merge back, I'll look at adding any missing features in a separate PR.

2023-10-02 08:39 UTC, sergio-costas commented
@robert-ancell Yes, everything works like a charm.

2023-10-02 22:19 UTC, closed without merging

2023-10-03 09:34 UTC, sergio-costas commented
@robert-ancell Agh, sorry! I didn't read the "in main" part, and I presumed that you was asking if this patch had everything that I needed.. I'll check if it does work.

2023-10-03 12:04 UTC, sergio-costas commented
Ok, I tested it with the code from the main branch of https://github.com/canonical/dbus.dart.git, and it works fine.